apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: irg7u6181-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: irg7u6181-python 
  name: irg7u6181-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: irg7u6181-python 
